<Project>

    <PropertyGroup Label="Build" Condition="'$(IsPlatformPackage)' == 'true'">
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Deterministic>true</Deterministic>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <PropertyGroup Label="NuGet info" Condition="'$(IsPlatformPackage)' == 'true'">
        <Title>$(AssemblyName)</Title>
        <PackageId>$(Title)</PackageId>
        <Authors>itmo-is-dev</Authors>
        <RepositoryUrl>https://github.com/itmo-is-dev/platform</RepositoryUrl>
        <RepositoryType>github</RepositoryType>
        <PackageProjectUrl>https://github.com/itmo-is-dev/platform</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>

        <PackageVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion)</PackageVersion>
        <AssemblyVersion>$(PackageVersion)</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup Label="NuGet items" Condition="'$(IsPlatformPackage)' == 'true'">
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <PropertyGroup Label="SourceLink"
                   Condition="'$(IsPlatformPackage)' == 'true' And '$(IsRoslynComponent)' != 'true'">
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup Label="SourceLink"
               Condition="'$(IsPlatformPackage)' == 'true' And '$(IsRoslynComponent)' != 'true'">
        <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all"/>
    </ItemGroup>

    <Import Project="$(MSBuildThisFileDirectory)src/Itmo.Dev.Platform.Options/Itmo.Dev.Platform.Options.targets"
            Condition="'$(_UsePlatformOptions)' == 'true'"/>

    <Import Project="$(MSBuildThisFileDirectory)src/Itmo.Dev.Platform.Options.MSBuild/Itmo.Dev.Platform.Options.MSBuild.targets"
            Condition="'$(_UsePlatformOptions)' == 'true'"/>

    <ItemGroup Condition="'$(_UsePlatformOptions)' == 'true'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)src/Itmo.Dev.Platform.Options/Itmo.Dev.Platform.Options.csproj"/>
        <ProjectReference Include="$(MSBuildThisFileDirectory)src/Itmo.Dev.Platform.Options.Analyzers/Itmo.Dev.Platform.Options.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all"/>
        <PackageReference Include="SourceKit.Runtime"/>
    </ItemGroup>

</Project>