<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <_UsePlatformOptions>true</_UsePlatformOptions>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Itmo.Dev.Platform.Observability\Itmo.Dev.Platform.Observability.csproj" />
    </ItemGroup>

</Project>
