namespace Itmo.Dev.Platform.BackgroundTasks.Tests.Arranges.RunWithAsync_ShouldExecuteStateMachine_WhenItContainsSuspends.States;

public sealed record SuspendingSuspendedTaskState : SuspendedTaskState;