<Project>

    <PropertyGroup>
        <TargetsForTfmSpecificContentInPackage>
            $(TargetsForTfmSpecificContentInPackage);GenerateJsonSchema
        </TargetsForTfmSpecificContentInPackage>
    </PropertyGroup>

    <Target Name="GenerateJsonSchema" AfterTargets="Build" Condition="'$(_DisablePlatformOptions)' != 'true'">

        <ItemGroup>
            <_SharedFrameworkPaths Include="@(FrameworkReference->'$(DOTNET_ROOT)/shared/%(Identity)/$(BundledNETCoreAppPackageVersion)')"/>
        </ItemGroup>

        <GenerateCurrentSchemaBuildTask
                TargetFramework="$(TargetFramework)"
                AssemblyPath="$(TargetPath)"
                SharedFrameworkPaths="@(_SharedFrameworkPaths)"
                ProjectAssetsFilePath="$(ProjectAssetsFile)"
                OutputPath="$(ProjectDir)$(AssemblyName).schema.json"
                Condition="'$(OutputType)' == 'Exe' and '$(IsTestProject)' != 'true'"/>

    </Target>

</Project>