name: platform-message-persistence

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/Itmo.Dev.Platform.Common/**'
      - 'src/Itmo.Dev.Platform.MessagePersistence/**'
      - 'src/Itmo.Dev.Platform.MessagePersistence.Postgres/**'
      - 'src/Itmo.Dev.Platform.Persistence.Postgres/**'
      - 'tests/Itmo.Dev.Platform.MessagePersistence.Tests/**'
      - 'tests/Itmo.Dev.Platform.MessagePersistence.Tests.Startup/**'
      - '.github/workflows/build-test-message-persistence.yaml'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build tests/Itmo.Dev.Platform.MessagePersistence.Tests/Itmo.Dev.Platform.MessagePersistence.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test tests/Itmo.Dev.Platform.MessagePersistence.Tests/Itmo.Dev.Platform.MessagePersistence.Tests.csproj -c Release --no-restore --no-build