name: platform-persistence-postgres

on:
  push:
    paths:
      - '.github/workflows/build-test-postgres.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'src/Itmo.Dev.Platform.Persistence.Postgres/**'
      - 'tests/Itmo.Dev.Platform.Persistence.Postgres.Tests/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ vars.ACTIONS_DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build tests/Itmo.Dev.Platform.Persistence.Postgres.Tests/Itmo.Dev.Platform.Persistence.Postgres.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test tests/Itmo.Dev.Platform.Persistence.Postgres.Tests/Itmo.Dev.Platform.Persistence.Postgres.Tests.csproj -c Release --no-restore --no-build