name: platform-background-tasks

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/Itmo.Dev.Platform.Common/**'
      - 'src/Itmo.Dev.Platform.BackgroundTasks/**'
      - 'src/Itmo.Dev.Platform.BackgroundTasks.Postgres/**'
      - 'src/Itmo.Dev.Platform.BackgroundTasks.Hangfire/**'
      - 'src/Itmo.Dev.Platform.BackgroundTasks.Hangfire.Postgres/**'
      - 'src/Itmo.Dev.Platform.Persistence.Postgres/**'
      - 'tests/Itmo.Dev.Platform.BackgroundTasks.Tests/**'
      - 'tests/Itmo.Dev.Platform.BackgroundTasks.Tests.Startup/**'
      - '.github/workflows/build-test-background-tasks.yaml'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100

      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build tests/Itmo.Dev.Platform.BackgroundTasks.Tests/Itmo.Dev.Platform.BackgroundTasks.Tests.csproj -c Release --no-restore

      - name: Test
        run: dotnet test tests/Itmo.Dev.Platform.BackgroundTasks.Tests/Itmo.Dev.Platform.BackgroundTasks.Tests.csproj -c Release --no-restore --no-build