name: platform-kafka

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/Itmo.Dev.Platform.Common/**'
      - 'src/Itmo.Dev.Platform.Kafka/**'
      - 'tests/Itmo.Dev.Platform.Kafka.Tests/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build tests/Itmo.Dev.Platform.Kafka.Tests/Itmo.Dev.Platform.Kafka.Tests.csproj -c Release --no-restore
  
  test:
    name: Test
    runs-on: ubuntu-latest

    #    As kafka tests are long running, they should be triggered manually, to avoid unnecessary wait time debounce-like way
    environment: testing
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test tests/Itmo.Dev.Platform.Kafka.Tests/Itmo.Dev.Platform.Kafka.Tests.csproj -c Release --no-restore