name: dotnet

on:
  pull_request:
    paths:
      - 'src/**'
      #     Ignored as there is a separate pipeline for these tests
      - '!src/Itmo.Dev.Platform.Kafka/**'
      - '!src/Itmo.Dev.Platform.Postgres/**'
      - '!src/Itmo.Dev.Platform.BackgroundTasks/**'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore