name: "publish packages"

on:
  push:
    branches: [ "chore/publish-new" ]
    paths:
      - 'src/**'
      - '.github/workflows/package-publish.yaml'
      - '.github/workflows/publish-*.sh'
      - '*.props'
      - '!samples'

jobs:
  find-changed-packages:
    name: "find changed packages"
    runs-on: ubuntu-latest
    
    outputs:
      packages: ${{ steps.changed-packages.outputs.changed-package-projects }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: find Directory.Build.props changes
        id: find-build
        continue-on-error: true
        run: |
          changes_count=$(git --no-pager diff ${{ github.event.before }} ${{ github.event.after }} Directory.Packages.props 2>/dev/null | grep -Ec '^\+ ') || echo x
          
          echo "$changes_count"
          echo changes-count="$changes_count" >> "$GITHUB_OUTPUT"

      - name: find Directory.Packages.props changes
        id: find-packages
        continue-on-error: true
        run: |
          changed_packages=$(git --no-pager diff ${{ github.event.before }} ${{ github.event.after }} Directory.Packages.props 2>/dev/null)
          changed_packages=$(echo "${changed_packages}" | grep '^\+ ' | grep -Eo 'Include="[a-zA-Z.]*"' | grep -Eo '".*"')
          changed_packages=$(echo "${changed_packages}" | tr -d '"' | sort | uniq)
          changed_packages=$(echo "${changed_packages}" | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
          changed_packages=$(echo "${changed_packages}" | tr -d '\n')

          echo "$changed_packages"
          echo changed-packages="$changed_packages" >> "$GITHUB_OUTPUT"

      - name: find package projects
        id: find-package-projects
        run: |
          package_projects=$(.github/workflows/publish-find-package-projects.sh | sort | uniq)
          package_projects=$(echo "$package_projects" | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
          package_projects=$(echo "$package_projects" | tr -d '\n')
          
          echo package-projects="$package_projects" >> "$GITHUB_OUTPUT"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: find changed package projects
        id: find-changed-package-projects
        if: ${{ steps.find-build.outputs.changes-count == 0 }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ALL_CHANGED_DEPENDENCIES: ${{ steps.find-packages.outputs.chnaged-packages }}
          PACKAGE_PROJECTS_JSON: ${{ steps.find-package-projects.outputs.package-projects }}
        run: |
          changed_package_projects=$(.github/workflows/publish-find-changed-packages.sh | sort | uniq | tr ' ' '\n')
          changed_package_projects=$(echo "$changed_package_projects" | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
          changed_package_projects=$(echo "$changed_package_projects" | tr -d '\n')
          
          echo changed-package-projects="$changed_package_projects" >> "$GITHUB_OUTPUT"

      - name: return all packages
        id: return-all-packages
        if: ${{ steps.find-build.outputs.changes-count != 0 }}
        run: |
          echo changed-package-projects=${{ steps.find-package-projects.outputs.package-projects }} >> "$GITHUB_OUTPUT"

      - name: calculate all changed packages
        id: changed-packages
        run: |
          selected=$(echo ${{ steps.find-changed-package-projects.outputs.changed-package-projects }} | jq -r 'values[]' | tr '\n' ' ')
          all=$(echo ${{ steps.return-all-packages.outputs.changed-package-projects }} | jq -r 'values[]' | tr '\n' ' ')
          
          all+="$selected"
          
          echo changed-package-projects="$all" >> "$GITHUB_OUTPUT"
  
  
  publish-package:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: find-changed-packages
    
    if: ${{
      needs.find-changed-packages.outputs.packages != '[]'
      && needs.find-changed-packages.outputs.packages != ''
      }}
    
    strategy:
      matrix:
        package: ${{ fromJSON(needs.find-changed-packages.outputs.packages) }}
    
    steps:
      - uses: actions/checkout@v4

      - name: write
        run: |
          echo ${{ matrix.package }}