name: "publish packages"

on:
  push:
    branches: [ "chore/publish-new" ]
    paths:
      - 'src/**'
      - '.github/workflows/package-publish.yaml'
      - '.github/workflows/publish-*.sh'
      - '*.props'
      - '!samples'

jobs:
  find-changed-packages:
    name: "find changed packages"
    runs-on: ubuntu-latest
    
    outputs:
      packages: ${{ steps.changed-packages.outputs.changed-package-projects }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: find Directory.Build.props changes
        id: find-build
        run: |
          changes_count=$(git --no-pager diff ${{ github.event.before }} ${{ github.event.after }} Directory.Build.props | grep -Ec '^\+ ') || :
          
          echo "$changes_count"
          echo changes-count="$changes_count" >> "$GITHUB_OUTPUT"

      - name: find Directory.Packages.props changes
        id: find-packages
        run: |
          changed_packages=$(git --no-pager diff ${{ github.event.before }} ${{ github.event.after }} Directory.Packages.props \
            | grep -E '^\+ ' \
            | grep -Eo 'Include="[a-zA-Z.]*"' \
            | grep -Eo '".*"' \
            | tr -d '"' \
            | sort \
            | uniq \
            | jq --raw-input --slurp 'split("\n") | map(select(. != ""))' \
            | tr -d '\n') || :

          echo "$changed_packages"
          echo changed-packages="$changed_packages" >> "$GITHUB_OUTPUT"

      - name: find package projects
        id: find-package-projects
        run: |
          package_projects=$(.github/workflows/publish-find-package-projects.sh | sort | uniq)
          package_projects=$(echo "$package_projects" | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
          package_projects=$(echo "$package_projects" | tr -d '\n')
          
          echo "$package_projects"
          echo package-projects="$package_projects" >> "$GITHUB_OUTPUT"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: find changed package projects
        id: find-changed-package-projects
        if: ${{ steps.find-build.outputs.changes-count == 0 }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          ALL_CHANGED_DEPENDENCIES: ${{ steps.find-packages.outputs.changed-packages }}
          PACKAGE_PROJECTS_JSON: ${{ steps.find-package-projects.outputs.package-projects }}
        run: |
          changed_package_projects=$(.github/workflows/publish-find-changed-packages.sh | sort | uniq | tr ' ' '\n')
          changed_package_projects=$(echo "$changed_package_projects" | jq --raw-input --slurp 'split("\n") | map(select(. != ""))')
          changed_package_projects=$(echo "$changed_package_projects" | tr -d '\n')
          
          echo changed-package-projects="$changed_package_projects" >> "$GITHUB_OUTPUT"

      - name: calculate all changed packages
        id: changed-packages
        env:
          SELECTED_PACKAGES: ${{ steps.find-changed-package-projects.outputs.changed-package-projects }}
          ALL_PACKAGES: ${{ steps.find-package-projects.outputs.package-projects }}
        run: |
          if [[ ${{ steps.find-build.outputs.changes-count }} -eq 0 ]]
          then
            echo changed-package-projects="$SELECTED_PACKAGES" >> "$GITHUB_OUTPUT"
          else
            echo changed-package-projects="$ALL_PACKAGES" >> "$GITHUB_OUTPUT"
          fi        
  
  
  publish-package:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: find-changed-packages
    
    environment: nuget.org
    
    if: ${{
      needs.find-changed-packages.outputs.packages != '[]'
      && needs.find-changed-packages.outputs.packages != ''
      }}
    
    strategy:
      matrix:
        package: ${{ fromJSON(needs.find-changed-packages.outputs.packages) }}
    
    steps:
      - uses: actions/checkout@v4

      - name: format csproj path
        id: csproj
        run: |
          csproj_path=$(find . -type d -name Itmo.Dev.Platform.${{ matrix.package }})/Itmo.Dev.Platform.${{ matrix.package }}.csproj
          csproj_dir=$(dirname "$csproj_path")
          
          echo path="$csproj_path" >> "$GITHUB_OUTPUT"
          echo dir="$csproj_dir" >> "$GITHUB_OUTPUT"
          
      - name: restore
        run: dotnet restore ${{ steps.csproj.outputs.path }}
        
      - name: build
        run: dotnet build ${{ steps.csproj.outputs.path }} -c Release --no-restore /p:PatchVersion=${{ github.run_number }}
        
      - name: publish
        run: |
          nuget_path=$(ls ${{ steps.csproj.outputs.dir }}/bin/Release/*.nupkg)
          echo "$nuget_path"