name: "publish packages"

on:
  push:
    branches: [ "chore/publish-new" ]
    paths:
      - 'src/**'
      - '.github/workflows/publish-new*'
      - '*.props'
      - '!samples'

jobs:
  find-package-projects:
    name: "find csproj files with packages"
    runs-on: ubuntu-latest
    
    outputs:
      changed-package-projects: ${{ steps.find-changed-package-projects.outputs.changed-package-projects }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: find package projects
        id: find-package-projects
        run: |
          package_projects=$(.github/workflows/publish-new-find-package-projects.sh)
          package_projects=$(echo "$package_projects" | jq --raw-input --slurp 'split("\n") | map(select(. != "")))
          
          echo "$package_projects"
          echo package-projects="$package_projects" >> "$GITHUB_OUTPUT"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: find changed package projects
        id: find-changed-package-projects
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          PACKAGE_PROJECTS_JSON: ${{ steps.find-package-projects.outputs.package-projects }}
        run: |
          package_projects=$(echo "$PACKAGE_PROJECTS_JSON" | jq -r 'values[]' | tr '\n' ' ')
          changed_package_projects=()

          for package_project in ${package_projects}
          do
            dependent_paths=$(.github/workflows/publish-new-find-csproj-dependencies.sh "${package_project}" | sort | uniq)
          
            for dependent_path in ${dependent_paths}
            do
              changes_count=$(echo "$ALL_CHANGED_FILES" | grep -Ec '"${dependent_path}")
          
              if [[ ! "$changes_count" -eq 0 ]]
              then
                changed_package_projects+=("${package_project})
                break
              fi
            done
          done
          
          changed_package_projects=$(echo "$changed_package_projects" | tr ' ' '\n' | jq --raw-input --slurp 'split("\n") | map(select(. != "")))
          echo changed-package-projects="$changed_package_projects" >> "$GITHUB_OUTPUT"
  
  
  publish-package-if-needed:
    name: "publish ${{ matrix.package-dir }}"
    runs-on: ubuntu-latest
    needs: find-package-projects
    
    strategy:
      matrix:
        package-dir: ${{ fromJSON(needs.find-package-projects.outputs.changed-package-projects) }}
    
    steps:
      - uses: actions/checkout@v4

      - name: write
        run: |
          echo ${{ matrix.package-dir }}